# Generated by Django 4.2.7 on 2023-11-14 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='delete_date',
            field=models.DateTimeField(default=None, verbose_name='delete published'),
        ),
        migrations.AlterField(
            model_name='application',
            name='create_user',
            field=models.CharField(max_length=50),
        ),
    ]
