# Generated by Django 4.2.7 on 2023-11-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_application_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='delete_date',
            field=models.DateTimeField(blank=True, default=None, verbose_name='date deleted'),
        ),
    ]
