# Generated by Django 4.2.7 on 2023-11-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_application_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='delete_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='date deleted'),
        ),
    ]
