# Generated by Django 4.2.7 on 2023-11-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_application_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='delete_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date deleted'),
        ),
    ]
