# Generated by Django 4.2.7 on 2023-11-14 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_alter_application_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='create_user',
            field=models.ForeignKey(default='anno', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
