# Generated by Django 4.2.7 on 2023-11-14 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_application_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('delete_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='date deleted')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('delete_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='date deleted')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.menu')),
            ],
        ),
    ]
