# Generated by Django 4.2.7 on 2023-11-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_menu_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
