# Generated by Django 4.2.7 on 2023-11-15 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.page'),
        ),
    ]
