# Generated by Django 4.2.7 on 2023-11-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_application_delete_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='app',
        ),
        migrations.AddField(
            model_name='menu',
            name='app',
            field=models.ManyToManyField(to='app.application'),
        ),
    ]
