# Generated by Django 4.2.7 on 2023-11-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_menu_app_menu_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
